### ISSUE TITLE
Support subdomains with dots

### ISSUE THREAD

**Issue by thasmo** [defunctzombie/localtunnel#67]
Is it possible to support dots in custom subdomains? Like `project.com.localtunnel.me`? That would be a really nice addition.

**Comment by defunctzombie** [comment]
Technically yes but honestly not worth it. I think this is taking the idea of temporary tunnels for testing and demo too far :)

**Comment by thasmo** [comment]
I wish you'd reconsider this. There's a real benefit when mapping hostnames automatically to directories using Apache or Nginx for developing purposes and combined with having the possibility to use localtunnel for testing this would be really useful. Of course at the moment this works fine with subdomains not containing dots, but it would be so much more flexible if dots would be allowed. Do you accept a PR, if I'd be able to get this running?

**Comment by defunctzombie** [comment]
One issue is you won't get https support. Another is that I am not certain
I can even setup the DNS to support this.

Why not just map using dashes? Also, iirc there is a --host option on the
client that lets you override the host header so you could use that with
some nginx or Apache setup.

**Comment by defunctzombie** [comment]
Since my email seems to have gotten misquoted, here is the additional part that might do what you want.

```
Why not just map using dashes? Also, iirc there is a --host option on the
client that lets you override the host header so you could use that with
some nginx or Apache setup.
```
