### ISSUE TITLE
Server down 502

### ISSUE THREAD

**Issue by wernight** [defunctzombie/localtunnel#69]
Seems the server http://localtunnel.me/ is down pretty frequently. It's really cool there is a free server and one can install the server himself. Just wondering what caused it to be down.

**Comment by cristiandouce** [comment]
Still down! :+1:

**Comment by wernight** [comment]
Back up :100:

**Comment by cristiandouce** [comment]
thx @defunctzombie

**Comment by wernight** [comment]
Down again :(

**Comment by defunctzombie** [comment]
Server sometimes crashes and does not restart itself. I haven't had the time to properly diagnose this issue.

**Comment by jessetane** [comment]
Down again

**Comment by jessetane** [comment]
Is the server just getting really heavy usage?

**Comment by defunctzombie** [comment]
Kinda. The docker/systemd don't play nice together so the process ends up not being able to restart sometimes, it gets stuck in some failed cgroup restart state. It is really annoying and I might switch to some other process restart tool just haven't had the time.

**Comment by jessetane** [comment]
systemd inside the (unprivileged?) container? what's the host OS / init system?

**Comment by defunctzombie** [comment]
CoreOS running docker 1.4.1. I just upgraded to docker 1.5.0 so lets see if that helps any.

**Comment by jessetane** [comment]
Cool - thanks a ton for providing this service, it's really very nice of you!

**Comment by wernight** [comment]
Thanks. May be you could describe how to use your docker image? https://github.com/defunctzombie/localtunnel-server/issues/22

**Comment by ElijahLynn** [comment]
Getting 502s right now.

**Comment by RomeHein** [comment]
Down again :/
It's in these occasions you understand how localtunnel is great... Honestly all others solutions are such a pain compare to localtunnel.

**Comment by nwheatle** [comment]
After using node to load localhost:3000 I ran:

<code>lt --port 3000</code>
<code>tunnel server offline: Request failed with status code 502, retry 1s</code>
<code>tunnel server offline: Request failed with status code 502, retry 1s</code>
<code>tunnel server offline: Request failed with status code 502, retry 1s</code>
...

does this mean the server is offline? Or am I doing something wrong?
