### ISSUE TITLE
Increase setMaxListeners on tunnel EventEmitter

### ISSUE THREAD

**Issue by davej** [defunctzombie/localtunnel#71]
Currently there is a `'close'` listener (and possibly other listeners too) set up for each of the *maximum* number of tcp connections. This means that using the reference server and defaults, it will set up 10 listeners.

By default EventEmitters will print a warning if more than 10 listeners are added for a particular event. So as soon as even one new close listener is added then node will start printing warnings to the console.

Not a huge issue but it can be confusing and send the programmer on a wild-goose chase looking for possible memory leaks.

This could probably be architected to not use listeners internally but the easy fix is to simply do `emitter.setMaxListeners(max_conn_count + 10)` so that warnings are not displayed after adding the first listener.

**Comment by bugs181** [comment]
Could you give us a little more information of where to add that code?

**Comment by davej** [comment]
Presumably you could just do something like:
```
tunnels.setMaxListeners(info.max_conn + 10);
```

[It could go on line 81 of Tunnel.js](https://github.com/defunctzombie/localtunnel/blob/master/lib/Tunnel.js#L81).

I haven't tested this to know if it's the correct place for sure though.

**Comment by davej** [comment]
Or even better:

```
tunnels.setMaxListeners(info.max_conn + (EventEmitter.defaultMaxListeners || 10));
```

`EventEmitter.defaultMaxListeners` was added in Node 0.12 so it will fall-back to 10 on earlier version of Node.

**Comment by bugs181** [comment]
Thanks for the help. Unfortunately neither of the above solutions. Still getting warnings.

    (node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
        at addListener (events.js:236:17)
        at once (events.js:262:8)
        at null.<anonymous> (.../node_modules/localtunnel/lib/Tunnel.js:104:14)

**Comment by davej** [comment]
Ah, ok, wasn't sure which event emitter was being used. Adding the following to line 91 instead should work so:

```javascript
tunnel.setMaxListeners(info.max_conn + (EventEmitter.defaultMaxListeners || 10));
```

**Comment by bugs181** [comment]
Same result, unless I'm doing something wrong. Perhaps I'll wait until you're able to test it out yourself.
