### ISSUE TITLE
Support nested subdomains

### ISSUE THREAD

**Issue by steve9001** [defunctzombie/localtunnel#77]
If localtunnel.me assigns me a subdomain
`your url is: https://gqgh.localtunnel.me`
it would be great to be able to visit arbitrary subdomains of the `gqgh` sudbomain, e.g. `https://foo.gqgh.localtunnel.me` and `https://bar.gqgh.localtunnel.me`.

**Comment by defunctzombie** [comment]
Can't do that because of how https certs work unfortunately :( Can't get wild-wildcard certs.
