### ISSUE TITLE
Persistent/Reusable addresses

### ISSUE THREAD

**Issue by mrasband** [defunctzombie/localtunnel#83]
When working with callbacks from other providers (e.g. oauth), it would be nice to have an option to use a persistent hash to remove the need to update API authorizations constantly.  It seems like a pretty solid premium feature users may pay for (myself included)

**Comment by defunctzombie** [comment]
Could you elaborate on this? Don't quite follow what you mean by persistent hash.

Also, wondering if you have checked out the [ngrok](https://ngrok.com/) project which is similar to localtunnel but does provide a few more premium features.

**Comment by mrasband** [comment]
I didn't read the docs, so ignore me. My bad.
