### ISSUE TITLE
How to do self hosting instead of exposing in localtunnel.me?

### ISSUE THREAD

**Issue by elgalu** [defunctzombie/localtunnel#84]
Is there a guide like https://github.com/inconshreveable/ngrok/blob/master/docs/SELFHOSTING.md#how-to-run-your-own-ngrokd-server that explains how to host your own localtunnel.me server?

**Comment by postmart** [comment]
+1

**Comment by defunctzombie** [comment]
Check out the server repo: https://github.com/defunctzombie/localtunnel-server
